#!/bin/bash
# check pyspark
SOURCE_REF=$(git rev-parse --short HEAD)
SHA_TAG="${DOCKER_TAG/-latest/}-$SOURCE_REF"
REAL_DOCKERPATH=${DOCKERFILE_PATH/docker\//}
if [[ $IMAGE_NAME == *"pyspark"* ]]; then
  BASE_IMG="$DOCKER_REPO:spark-$SOURCE_REF"
  # shellcheck disable=SC2046,SC2006
  docker build --build-arg base_img="$BASE_IMG" --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF="$SOURCE_REF" -f "$REAL_DOCKERPATH" -t "$IMAGE_NAME" -t "$DOCKER_REPO:$SHA_TAG" .
else
  # shellcheck disable=SC2046,SC2006
  docker build -f "$REAL_DOCKERPATH" --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF="$SOURCE_REF" -t "$IMAGE_NAME" -t "$DOCKER_REPO:$SHA_TAG" .
fi
