#!/bin/bash
SOURCE_REF=$(git rev-parse --short HEAD)
SHA_TAG="${DOCKER_TAG/-latest/}-$SOURCE_REF"
docker tag "$IMAGE_NAME" "$DOCKER_REPO:$SHA_TAG"
docker push "$DOCKER_REPO:$SHA_TAG"

# Check if there's a chained build here ( for pyspark )
if [[ $DOCKER_REPO == "spark-eks" ]]; then 
  if [[ $DOCKER_TAG != *"pyspark"* ]]; then
    # shellcheck disable=SC2001,SC2086
    PYSPARK_TAG="py${DOCKER_TAG}"
    curl -X POST -H "Content-Type: application/json" --data "{ \"docker_tag\": \"$PYSPARK_TAG\" }" "$TRIGGER_URL"
  fi
fi